name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Startup
        uses: actions/checkout@v4

      - name: Download PHP
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: PHP-Linux-x86_64-PM5.tar.gz
          repo: pmmp/PHP-Binaries
          version: "tags/php-8.2-latest"

      - name: Unpack PHP
        run: tar -xzvf PHP-Linux-x86_64-PM5.tar.gz

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Download Composer
        run: curl -o composer.phar "https://getcomposer.org/composer-stable.phar"

      - name: Install Composer dependencies
        run: ./bin/php7/bin/php composer.phar install --no-progress --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run PHPStan
        run: ./bin/php7/bin/php vendor/bin/phpstan.phar analyze --no-progress
